### ISSUE TITLE
New repository template

### ISSUE THREAD

**Issue by hbourgeot** [romsar/gonertia#5]
Hello! Happy to help contribute to this repository, I tried to replicate the example that is in this repository but it was not successful, there are several things that are failing such as directories or compilation of tailwindcss, so to help new users and popularize this wonderful tool I made this repo template with executable code, almost ready to use.

Without further ado, I say goodbye leaving the link to the [repository template](https://github.com/hbourgeot/gonertia_vue_example).

Also, I propose to create an organization called gonertia where we can upload the gonertia code and repository templates and some other related things that are going to be done in the short, medium or long term

**Comment by romsar** [comment]
Hello, Henrry!

Thanks for your feedback, and I'm glad you use Gonertia!
Because Gonertia is just an Inertia.js adapter for Go, and it already supports all the features that official Laravel does - I don't see a lot of work on this project in the future.
All that remains for us is to support the new updates that are coming out in Inertia and I guarantee that I will do this as they come out, because I use Inertia.js very often.
For this reason, the creation of an organization, at this stage, seems superfluous to me.
In addition, there are a lot of popular projects that also exist without organization and without any problems, for example -  [https://github.com/jackc/pgx](https://github.com/jackc/pgx).

Regarding the fact that you failed to run the example, could you tell me please what needs to be changed in the code to fix this? It would be nice to see some kind of pull request, or, if you allow, I can just leave a link to your repository, but then I have a request - use English comments instead of Spanish ones to make running the example more convenient for English-speaking users.

**Comment by hbourgeot** [comment]
The errors I had were not in the code, they were in the build, since the css is not included unless it is imported in the app.js, otherwise... the tailwind styles are not builded.

On the other hand, those comments in Spanish are from chatgpt, it was my mistake to leave them hehe, but I must make some good ones in English as well as a readme, but you can leave the link. In addition to that one in vue, I made [this one in svelte](https://github.com/hbourgeot/gonertia_svelte_example)

I'll close this issue, I'm glad to help!

**Comment by romsar** [comment]
Huge thanks, I'll leave links to your repositories instead of a link to the examples folder.
